solve:
  timeLimit: 5
  optimalityGap: 0.2
  roleCouplingWeight: 5
  rotationBeatWeight: 0
  spotterMode: 1
  allowNoSpotter: false

server:
  ip: "127.0.0.1"
  port: 11080
  requestDirectory: "/tmp/jres_solver/requests/"
